# Generated by Django 5.0.6 on 2024-05-13 18:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WatchlistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="watchlists",
            field=models.ManyToManyField(to="users.watchlistitem"),
        ),
    ]
