# Generated by Django 5.0.6 on 2024-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_watchlistitem_user_watchlists"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlistitem",
            name="item",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
