# Generated by Django 5.0.6 on 2024-05-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_watchlistitem_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="watchlists",
        ),
        migrations.AddField(
            model_name="user",
            name="watchlists",
            field=models.JSONField(default=list),
        ),
    ]
