# Generated by Django 5.0.6 on 2024-05-13 18:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_remove_user_watchlists_user_watchlists"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WatchlistItem",
        ),
    ]
