# Generated by Django 5.0.6 on 2024-05-13 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_delete_watchlistitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.MinLengthValidator(8),
                    django.core.validators.RegexValidator(
                        message="Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character.",
                        regex="^(?=.*[A-Z])(?=.*[a-z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,}$",
                    ),
                ],
            ),
        ),
    ]
